[package]
name = "git-credential"
version = "0.1.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
url = "2.1.0"
log = "0.4.8"
snafu = "0.4.4"
