[package]
name = "git-credential"
version = "0.1.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
log = "0.4.8"
snafu = "0.4.4"
